
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analisadorSintatico;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int NUMERO = 45;
  public static final int RESTO = 6;
  public static final int PONTOVIRGULA = 16;
  public static final int SOMA = 2;
  public static final int DIFERENTE = 11;
  public static final int MULTIPLICACAO = 4;
  public static final int INT = 34;
  public static final int MAIORIGUAL = 15;
  public static final int VIRGULA = 18;
  public static final int NEGACAO = 7;
  public static final int PONTO = 17;
  public static final int E = 8;
  public static final int STATIC = 29;
  public static final int IDENTIFICADOR = 46;
  public static final int MENORIGUAL = 13;
  public static final int IGUAL = 10;
  public static final int OU = 9;
  public static final int CLASS = 27;
  public static final int ABRECHAVES = 21;
  public static final int FECHACHAVES = 22;
  public static final int IF = 36;
  public static final int MAIN = 32;
  public static final int THIS = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 31;
  public static final int RETURN = 38;
  public static final int MAIOR = 14;
  public static final int TRUE = 43;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int MENOR = 12;
  public static final int VOID = 30;
  public static final int DIVISAO = 5;
  public static final int ELSE = 37;
  public static final int ABRECOL = 23;
  public static final int ABREPAR = 19;
  public static final int WHILE = 35;
  public static final int PUBLIC = 26;
  public static final int EXTENDS = 28;
  public static final int SYSTEMOUTPRINTLN = 42;
  public static final int STRING = 33;
  public static final int FECHAPAR = 20;
  public static final int FECHACOL = 24;
  public static final int ATRIBUI = 25;
  public static final int FALSE = 44;
  public static final int SUBTRACAO = 3;
  public static final int LENGTH = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SOMA",
  "SUBTRACAO",
  "MULTIPLICACAO",
  "DIVISAO",
  "RESTO",
  "NEGACAO",
  "E",
  "OU",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MENORIGUAL",
  "MAIOR",
  "MAIORIGUAL",
  "PONTOVIRGULA",
  "PONTO",
  "VIRGULA",
  "ABREPAR",
  "FECHAPAR",
  "ABRECHAVES",
  "FECHACHAVES",
  "ABRECOL",
  "FECHACOL",
  "ATRIBUI",
  "PUBLIC",
  "CLASS",
  "EXTENDS",
  "STATIC",
  "VOID",
  "BOOLEAN",
  "MAIN",
  "STRING",
  "INT",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "LENGTH",
  "THIS",
  "NEW",
  "SYSTEMOUTPRINTLN",
  "TRUE",
  "FALSE",
  "NUMERO",
  "IDENTIFICADOR"
  };
}

